import { useEffect, useState } from 'react'
import { ChevronLeft, ChevronRight, Share2 } from 'lucide-react'

import { ErrorState } from '@/components/common/error-state'
import { AppHeader } from '@/components/layout/app-header'
import { PageContainer } from '@/components/layout/page-container'
import { Button } from '@/components/ui/button'
import { Skeleton } from '@/components/ui/skeleton'
import { RecapCard } from '@/features/recap/components/recap-card'
import { RecapShareTargets } from '@/features/recap/components/recap-share-targets'
import { useMonthlyRecap } from '@/features/recap/use-monthly-recap'
import { useProfile } from '@/hooks/use-profile'
import { buildRecapImageFile } from '@/services/share/recap-image'
import { discoverService } from '@/services/discover/discover-service'
import { shareService } from '@/services/share/share-service'

/**
 * `/recap` — a member's own monthly recap. Read-only and free for everyone
 * (see `docs/monetization.md`): nothing here is gated behind Buddy+.
 */
export function MonthlyRecapPage() {
  const { profile } = useProfile()
  const { recap, isLoading, error, canGoToNextMonth, goToPreviousMonth, goToNextMonth } =
    useMonthlyRecap()
  const [isSharing, setIsSharing] = useState(false)
  const [shareFeedback, setShareFeedback] = useState('')

  const memberName = profile?.displayName ?? 'Your'
  const [buddyNames, setBuddyNames] = useState<ReadonlyMap<string, string>>(new Map())

  // One batched `publicProfiles` read for everyone in the recap — never a
  // request per person, and never `users/{uid}`.
  useEffect(() => {
    const ids = recap?.buddies.map(({ userId }) => userId) ?? []
    if (ids.length === 0) {
      setBuddyNames(new Map())
      return
    }
    let active = true
    discoverService
      .getProfiles(ids)
      .then((profiles) => {
        if (!active) return
        setBuddyNames(new Map(profiles.map((found) => [found.userId, found.displayName])))
      })
      .catch(() => {})
    return () => {
      active = false
    }
  }, [recap])

  const share = async () => {
    if (!recap) return
    setIsSharing(true)
    setShareFeedback('')
    try {
      const file = await buildRecapImageFile(recap, memberName)
      const outcome = await shareService.shareFile({
        file,
        title: `${memberName}'s ${recap.monthLabel} — Sports Buddy`,
        text: `${memberName}'s ${recap.monthLabel} recap on Sports Buddy`,
      })
      if (outcome === 'downloaded') setShareFeedback('Image saved — share it from your gallery.')
    } catch (shareError) {
      setShareFeedback(
        shareError instanceof Error ? shareError.message : "We couldn't share your recap.",
      )
    } finally {
      setIsSharing(false)
    }
  }

  return (
    <>
      <AppHeader title="Monthly recap" size="wide" variant="detail" />
      <PageContainer size="wide">
        <div className="mx-auto flex w-full max-w-narrow flex-col gap-6 md:gap-8">
          <div className="flex items-center justify-between">
            <Button
              variant="ghost"
              size="icon-sm"
              aria-label="Previous month"
              onClick={goToPreviousMonth}
              disabled={isLoading}
            >
              <ChevronLeft className="size-5" />
            </Button>
            <span className="text-title text-foreground">
              {recap?.monthLabel ?? ' '}
            </span>
            <Button
              variant="ghost"
              size="icon-sm"
              aria-label="Next month"
              onClick={goToNextMonth}
              disabled={isLoading || !canGoToNextMonth}
            >
              <ChevronRight className="size-5" />
            </Button>
          </div>

          {isLoading && <Skeleton className="h-96 w-full rounded-2xl" />}
          {!isLoading && error && <ErrorState title={error} />}
          {!isLoading && !error && recap && (
            <div className="flex flex-col gap-4">
              <RecapCard recap={recap} memberName={memberName} buddyNames={buddyNames} />

              {/*
                A recap is computed live from the sessions that have already
                happened, so it fills in as the month goes and stops changing
                once the month ends. Nothing is generated by a job — there is no
                server to run one, and saying otherwise would be a claim we
                cannot keep.
              */}
              <p className="text-caption text-muted-foreground">
                This recap updates as you play and is complete once{' '}
                {recap.monthLabel} ends. Use the arrows to look back at any
                earlier month.
              </p>

              <Button disabled={isSharing} onClick={() => void share()}>
                <Share2 className="size-4" />
                {isSharing ? 'Preparing…' : 'Share recap'}
              </Button>

              <RecapShareTargets
                recap={recap}
                memberName={memberName}
                isPreparing={isSharing}
                onSaveImage={() => void share()}
              />
              {shareFeedback && (
                <p role="status" className="text-center text-body-small text-muted-foreground">
                  {shareFeedback}
                </p>
              )}
            </div>
          )}
        </div>
      </PageContainer>
    </>
  )
}
