import type { DiscoveryProfile } from '@/types/discovery-profile'

/**
 * Development candidates for `VITE_DATA_SOURCE=mock`. Deliberately varied
 * across sports, skills, areas, intents and availability so filtering can be
 * tested properly. No emails, no photos, no coordinates — same allowlist as a
 * real projection.
 */
export const MOCK_CANDIDATES = [
  {
    userId: 'buddy_aina',
    displayName: 'Aina',
    photoUrl: null,
    bio: 'Weekend badminton and the occasional easy run.',
    sports: [
      { sportId: 'badminton', skillLevel: 'intermediate' },
      { sportId: 'running', skillLevel: 'casual' },
    ],
    intents: ['casual', 'training'],
    preferredIntensity: 'moderate',
    availability: [
      { day: 'saturday', periods: ['afternoon', 'evening'] },
      { day: 'sunday', periods: ['morning'] },
    ],
    area: 'petaling-jaya',
    budget: { min: 20, max: 40 },
    profileCompleteness: 100,
    discoverable: true,
    updatedAt: '2026-08-30T09:00:00.000Z',
  },
  {
    userId: 'buddy_jason',
    displayName: 'Jason',
    photoUrl: null,
    bio: 'Climbing four times a week. Happy to belay beginners.',
    sports: [
      { sportId: 'climbing', skillLevel: 'advanced' },
      { sportId: 'gym', skillLevel: 'intermediate' },
    ],
    intents: ['training', 'competitive'],
    preferredIntensity: 'high',
    availability: [
      { day: 'monday', periods: ['evening'] },
      { day: 'wednesday', periods: ['evening'] },
      { day: 'saturday', periods: ['morning'] },
    ],
    area: 'subang-jaya',
    budget: { min: 40, max: 60 },
    profileCompleteness: 100,
    discoverable: true,
    updatedAt: '2026-08-29T12:30:00.000Z',
  },
  {
    userId: 'buddy_mei',
    displayName: 'Mei',
    photoUrl: null,
    bio: 'Just started pickleball and loving it.',
    sports: [{ sportId: 'pickleball', skillLevel: 'beginner' }],
    intents: ['social', 'casual'],
    preferredIntensity: 'relaxed',
    availability: [
      { day: 'tuesday', periods: ['evening'] },
      { day: 'saturday', periods: ['afternoon'] },
    ],
    area: 'kuala-lumpur',
    budget: { min: 10, max: 20 },
    profileCompleteness: 100,
    discoverable: true,
    updatedAt: '2026-08-28T04:15:00.000Z',
  },
  {
    userId: 'buddy_daniel',
    displayName: 'Daniel',
    photoUrl: null,
    bio: 'Futsal every Friday, always short one player.',
    sports: [
      { sportId: 'futsal', skillLevel: 'intermediate' },
      { sportId: 'gym', skillLevel: 'casual' },
    ],
    intents: ['casual', 'social'],
    preferredIntensity: 'high',
    availability: [{ day: 'friday', periods: ['evening'] }],
    area: 'cheras',
    budget: { min: 10, max: 20 },
    profileCompleteness: 90,
    discoverable: true,
    updatedAt: '2026-08-27T15:45:00.000Z',
  },
  {
    userId: 'buddy_farah',
    displayName: 'Farah',
    photoUrl: null,
    bio: 'Morning runner training for a half marathon.',
    sports: [
      { sportId: 'running', skillLevel: 'advanced' },
      { sportId: 'gym', skillLevel: 'intermediate' },
    ],
    intents: ['training'],
    preferredIntensity: 'high',
    availability: [
      { day: 'tuesday', periods: ['morning'] },
      { day: 'thursday', periods: ['morning'] },
      { day: 'sunday', periods: ['morning'] },
    ],
    area: 'shah-alam',
    budget: { min: 0, max: 10 },
    profileCompleteness: 100,
    discoverable: true,
    updatedAt: '2026-08-26T22:10:00.000Z',
  },
  {
    userId: 'buddy_amir',
    displayName: 'Amir',
    photoUrl: null,
    bio: 'Badminton doubles, weeknights mostly.',
    sports: [{ sportId: 'badminton', skillLevel: 'advanced' }],
    intents: ['competitive', 'training'],
    preferredIntensity: 'high',
    availability: [
      { day: 'monday', periods: ['evening'] },
      { day: 'thursday', periods: ['evening'] },
    ],
    area: 'subang-jaya',
    budget: { min: 20, max: 40 },
    profileCompleteness: 90,
    discoverable: true,
    updatedAt: '2026-08-25T11:05:00.000Z',
  },
  {
    userId: 'buddy_chloe',
    displayName: 'Chloe',
    photoUrl: null,
    bio: 'Bouldering and coffee afterwards, non-negotiable.',
    sports: [
      { sportId: 'climbing', skillLevel: 'casual' },
      { sportId: 'badminton', skillLevel: 'beginner' },
    ],
    intents: ['social', 'casual'],
    preferredIntensity: 'relaxed',
    availability: [
      { day: 'wednesday', periods: ['evening'] },
      { day: 'saturday', periods: ['afternoon', 'evening'] },
    ],
    area: 'petaling-jaya',
    budget: { min: 20, max: 40 },
    profileCompleteness: 100,
    discoverable: true,
    updatedAt: '2026-08-24T08:20:00.000Z',
  },
  {
    userId: 'buddy_wei_jian',
    displayName: 'Wei Jian',
    photoUrl: null,
    bio: 'Tennis on weekends, rusty but improving.',
    sports: [
      { sportId: 'tennis', skillLevel: 'casual' },
      { sportId: 'running', skillLevel: 'beginner' },
    ],
    intents: ['casual'],
    preferredIntensity: 'moderate',
    availability: [
      { day: 'saturday', periods: ['morning', 'afternoon'] },
      { day: 'sunday', periods: ['afternoon'] },
    ],
    area: 'puchong',
    budget: { min: 20, max: 40 },
    profileCompleteness: 90,
    discoverable: true,
    updatedAt: '2026-08-23T13:40:00.000Z',
  },
  {
    userId: 'buddy_nadia',
    displayName: 'Nadia',
    photoUrl: null,
    bio: 'Gym in the mornings, basketball when someone drags me out.',
    sports: [
      { sportId: 'gym', skillLevel: 'advanced' },
      { sportId: 'basketball', skillLevel: 'beginner' },
    ],
    intents: ['training', 'social'],
    preferredIntensity: 'moderate',
    availability: [
      { day: 'monday', periods: ['morning'] },
      { day: 'wednesday', periods: ['morning'] },
      { day: 'friday', periods: ['morning'] },
    ],
    area: 'ampang',
    budget: { min: 0, max: 10 },
    profileCompleteness: 100,
    discoverable: true,
    updatedAt: '2026-08-22T06:55:00.000Z',
  },
  {
    userId: 'buddy_ryan',
    displayName: 'Ryan',
    photoUrl: null,
    bio: 'Basketball runs on Sunday evenings in Kepong.',
    sports: [{ sportId: 'basketball', skillLevel: 'intermediate' }],
    intents: ['casual', 'competitive'],
    preferredIntensity: 'high',
    availability: [{ day: 'sunday', periods: ['evening'] }],
    area: 'kepong',
    budget: { min: 0, max: 10 },
    profileCompleteness: 90,
    discoverable: true,
    updatedAt: '2026-08-21T17:25:00.000Z',
  },
] as const satisfies readonly DiscoveryProfile[]
